services:
  backend-engine:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: netflow_backend_engine
    volumes:
      - ./data:/workspace/data
      - ./models:/workspace/models
    networks:
      - netflow-soc-network

  web-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: netflow_analytics_app
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/workspace
      - ./data:/workspace/data
      - ./models:/workspace/models
    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434
    depends_on:
      - backend-engine
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - netflow-soc-network

networks:
  netflow-soc-network:
    driver: bridge
